[package]
name = "mercury"
version = "0.0.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.0"
tokio = { version = "1.28", features = ["rt-multi-thread"] }
reqwest = { version = "0.11", features = ["json"] }
once_cell = "1.17"
cached = "0.43"
url = { version = "2.3", features = ["serde"] }
axum = "0.6"
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
