[package]
name = "mercury"
version = "0.0.0"
edition = "2021"

[dependencies]
dotenvy_macro = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.0"
serde_json = "1.0"
tokio = { version = "1.28", features = ["rt-multi-thread"] }
reqwest = { version = "0.11", features = ["json"] }
cached = "0.43"
url = "2.3"
url_serde = "0.2"
