name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      # Docker is preinstalled.
      - run: nix build .#dockerImage && ./result | docker load
      - run: |
          echo ${{ secrets.FLY_AUTH_TOKEN }} | docker login -u x --password-stdin registry.fly.io/mercury-test
          docker tag mercury registry.fly.io/mercury-test:latest
          docker push registry.fly.io/mercury-test:latest
      - run: nix develop .#ops -c flyctl deploy -t ${{ secrets.FLY_AUTH_TOKEN }}
